### ISSUE TITLE
Error in tm_bryan.set_omega

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/maxent#14]
Dear @Manuel,
I am trying to supply the G_tau for analytic continuation, but I am getting the following error.

from pytriqs.archive import HDFArchive
from triqs_maxent import *
from triqs_maxent.tau_maxent import TauMaxEnt
# load G_tau from h5 file
h5 = HDFArchive('SrVO3.h5', 'r')
# show the content of h5 file
print h5
# loard the desired Gtau
G_tau = h5['D=1']
tm_bryan = TauMaxEnt(cost_function='bryan', probability='normal')
# this will set the  loaded G_tau
tm_bryan.set_G_tau(G_tau((1000, 1, 2).real)
tm_bryan.set_omega = HyperbolicOmegaMesh(omega_min=-15, omega_max=15, n_points=400)
tm_bryan.alpha_mesh = LogAlphaMesh(alpha_min=5e-5, alpha_max=500, n_points=20)
# set the error carefully
tm_bryan.set_error(10*err)

result = tm_bryan.run()

The error here is 

 File "MAC1.py", line 13
    tm_bryan.set_omega = HyperbolicOmegaMesh(omega_min=-15, omega_max=15, n_points=400)
           ^
SyntaxError: invalid syntax

I will be helpful for your suggestion.

Best Regards
CMTCL

**Comment by mzingl** [comment]
tm_bryan.set_G_tau(G_tau((1000, 1, 2).real)

This can't work because there is a ")" missing. For every "(" you need one ")".
Without a solid knowledge of python you should not be using TRIQS at all.

The TRIQS maxent code for SrVO3 works perfectly fine and the documentation is
very clear. I know of multiple people who had no issues whatsoever to use it
and to supply G(tau).

We have repeatable told you to adhere to the common etiquette in posting issues.
This does include formatting the issues properly. Further my github tag is @mzingl 
and not the one you are using. Do not tag the wrong people!
Because of repeated violations, we blocked you under your old user name.
You are spamming our issue lists with things which are NOT issues at all.

I'm closing this issues and I will not reply to any further issues.

Best, Manuel
