### ISSUE TITLE
ERROR IN CONVERTING Gaux_w from Aaux_w 

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/maxent#15]
Dear TRIQS/MAXENT Team,
I want to obtain real-frequency self energy. I successfully run MAXENT. In order to get real-frequency self energy, I used InversionSigmaContinuator(isc), using the relevant command

with HDFArchive('SrVO3.h5', 'r') as ar:
    Sigma_iw = ar['dmft_output']['Sigma_iw']
    for key in Sigma_iw.indices:
        res[key] = ar['dmft_output/Sigma_iw/' + key]

# get S_w from the auxilliary spectral function Aaux_w
Aaux_w = {}
w = res['up_0'].data

for key in Sigma_iw.indices:
    #print(key)
    #print(res[key])
    res[key].analyzer_results['LineFitAnalyzer']['A_out'] = Aaux_w[key]

isc.set_Gaux_w_from_Aaux_w(Aaux_w, w, np_interp_A=10000,
                           np_omega=4000, w_min=-1.0, w_max=1.0)

# save SigmaContinuator again (now it contains S_w)
with HDFArchive('SrVO3_maxent.h5' , 'a') as ar:
    ar['isc'] = isc

By using it, I am getting the following error.
Traceback (most recent call last):
  File "maxent.py", line 74, in <module>
    res[key].analyzer_results['LineFitAnalyzer']['A_out'] = Aaux_w[key]
KeyError: 'up_2'

I have been trying  a lot to sort-out the error. 
can any one suggest what is the error here?

Best Regards
CMTCL

**Comment by the-hampel** [comment]
Hi CMTCL,
This error is related to your previous problem. In your h5 archive the object is now present, but it does not have a spin block called 'up_2' .  Please make yourself familiar with the hdfview tool: https://packages.ubuntu.com/de/bionic/hdfview , also available for other operating systems. With this graphical tool you can explore your h5 archives and see the structure. Anyway, can you print res[kes] and show the output? And it would be also very useful, if you could post your full script which you used here. But please `as code`, otherwise it is very hard to read.  At the moment I cannot say why your object has no key 'up_2'. There is no way to see this from your given information.
Best,
Alex

**Comment by cmtcl18** [comment]
Dear Alex,
I am very much thankful to you. I apologize, due to certain unavoidable reason I did not make early reply. Here I am giving my full script as code for converting Sigma_w from Sigma_iw.

from __future__ import absolute_import, print_function
from pytriqs.archive import HDFArchive
from triqs_maxent import *
from pytriqs.archive import *
import numpy as np
### load self-energy from h5 file
##### load G_tau
h5 = HDFArchive('SrVO3.h5', 'r')
### show the content
#print(h5['dmft_output'])
### load the desired G_tau
G_tau = h5['dmft_output/G_tau/up_0']

### set and run maxent
tm = TauMaxEnt(cost_function='bryan', probability='normal')
### set the loaded G_tau
tm.set_G_tau(G_tau[0,0].real)

tm.omega = HyperbolicOmegaMesh(omega_min=-15, omega_max=15, n_points=400)
tm.alpha_mesh = LogAlphaMesh(alpha_min=5e-5, alpha_max=500, n_points=20)

### set error 
tm.set_error(1.e-2)

### run it
res = tm.run()

### Initialize SigmaContinuator
with HDFArchive('SrVO3.h5', 'r') as ar:
    Sigma_iw = ar['dmft_output']['Sigma_iw']
    dc = ar['user_data/dc_energ/0']

isc = InversionSigmaContinuator(Sigma_iw, dc)

### save the result to h5-file
res = {}
with HDFArchive('SrVO3_maxent.h5', 'a') as ar:
    for key in res:
        print(res[key])
        ar['maxent_result_'] = res[key].data
    ar['isc'] = isc


with HDFArchive('SrVO3.h5', 'r') as ar:
    Sigma_iw = ar['dmft_output']['Sigma_iw']
    for key in Sigma_iw.indices:
        res[key] = ar['dmft_output/Sigma_iw/' + key]
        #print(res[key])



# get S_w from the auxilliary spectral function Aaux_w


Aaux_w = {}
w = res['up_0'].omega

for key in res:
    print(res[key])
    res[key].analyzer_results['LineFitAnalyzer']['A_out'] = Aaux_w[key] 

isc.set_Gaux_w_from_Aaux_w(Aaux_w, w, np_interp_A=10000,
                           np_omega=4000, w_min=-1.0, w_max=1.0)

# save SigmaContinuator again (now it contains S_w)
with HDFArchive('SrVO3_maxent.h5' , 'a') as ar:
    ar['isc'] = isc

when I keep w = res['up_0'].omega, I am getting this error.
MaxEnt loop finished in 0:02:06.469520
Traceback (most recent call last):
  File "maxent.py", line 70, in <module>
    w = res['up_0'].omega
AttributeError: 'Gf' object has no attribute 'omega.

when I change w =  res['up_0'].omega to  w = res['up_0'].data, it is not showimg error for 'w'. 

MaxEnt loop finished in 0:02:06.003223
up_2
Traceback (most recent call last):
  File "maxent.py", line 60, in <module>
    res[key].analyzer_results['LineFitAnalyzer']['A_out'] = Aaux_w[key] 
KeyError: 'up_2'

I will be thankful for your suggestion.

Best Regards
CMTCL

**Comment by the-hampel** [comment]
Hi,
first thing. Please do format your posts. Otherwise it is incredible hard to read! This is supposed to be python source code so please format it as such. There is the preview tab where you can check how your post looks like before you actually post it. I hope you see the problem. Your text is interpreted as markdown, so every comment in your code is made bold! Also I cannot see the difference between source code, and output from running the script. In the toolbar you can find a symbol looking like '<>'  , click this and insert the python source code in-between! If you have a block of code use the markers like this:  \``` python code here \```.   This will help us a lot to understand afterwards what is going on. For example this is completely unreadable:
# load res and SigmaContinuator from h5-file
res = {}
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
    S_iw = ar['S_iw']
    for key in S_iw.indices:
        res[key] = ar['maxent_result_' + key]
    isc = ar['isc']

but this:
```
# load res and SigmaContinuator from h5-file
res = {}
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
    S_iw = ar['S_iw']
    for key in S_iw.indices:
        res[key] = ar['maxent_result_' + key]
    isc = ar['isc']
```
is showing nicely what is going on in your script, where I used \``` source code here \``` . Please do so the next time!

**Comment by the-hampel** [comment]
Regarding your problem. If I see it correctly you define res and run maxent  as 
```
tm.set_G_tau(G_tau[0,0].real)
...
res = tm.run()
```
But a bit later you define 
```
res = {}
```
so than `res` is now empty again? What did you want to achieve here? I think this is the main cause of your problem. I see that you are using parts of the example code shown here:  https://triqs.github.io/maxent/master/guide/sigma_continuator.html . Why are you not using the whole source code provided there? You should do something like
```
# Load self-energy from h5-file
with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
    S_iw = ar['S_iw']
    dc = ar['dc']

# Initialize SigmaContinuator, we use the
# double counting (dc) as constant shift c.
isc = InversionSigmaContinuator(S_iw, dc)

# run TauMaxEnt for each block and collect results
# in dict res.
res = {}
for name, gaux_iw in isc.Gaux_iw:
    tm = TauMaxEnt()
    tm.set_G_iw(gaux_iw)
    tm.set_error(1e-4)
    tm.omega = HyperbolicOmegaMesh(omega_min=-10, omega_max=10, n_points=500)
    tm.alpha_mesh = LogAlphaMesh(alpha_min=1e-2, alpha_max=1e2, n_points=30)
    res[name] = tm.run()
```
Then afterwards `res` will also contain a key `up_2` and `.omega`. I hope that helps somehow. Try to run the above code for your SrVO3 example first.

**Comment by cmtcl18** [comment]
Dear Alex,
Thank yoy very much for your suggestion. I successfully converted  `Sigma_iw to Sigma_w` after converting `S_iw to S_w`. In my SrVO3.h5 file I do not have `dft_symmpar_input`, for which I am getting error during DOS calculation.  
Since it is not related to TRIQS/MAXENT issues, If you want me to open a new issue, then I will create a new issue in TRIQS/DFTTools explicitly. 
Can I know what is the reason for the problem? 

I will be thankful for your suggestion.

Best Regards
CMTCL

**Comment by the-hampel** [comment]
Hi CMTCL,
very good. I am glad that it helped. Yes please open a another issue on dft_tools, explaining also your steps to create the h5 archive, and also what exactly you tried to plot. Usually the converter from DFT to h5 should generate also `dft_symmpar` input, as far as I know. 
Best,
Alex
