### ISSUE TITLE
Sigma_w

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#9]
Dear all
Hi
I run the "sigma_continuator_SRO_1and2.py" that are implemented in maxentropy program.
"
# load res and SigmaContinuator from h5-file
res = {}
with HDFArchive('srvo3.h5', 'r') as ar:
    S_iw = ar['dmft_output']['Sigma_iw']
    for key in S_iw.indices:
        res[key] = ar['maxent_result_' + key]
    ar['isc'] = isc

# get S_w from the auxilliary spectral function Aaux_w
Aaux_w = {}
w = res['up_0'].omega
for key in res:
    Aaux_w[key] = res[key].analyzer_results['LineFitAnalyzer']['A_out']

isc.set_Gaux_w_from_Aaux_w(Aaux_w, w, np_interp_A=10000,
                           np_omega=4000, w_min=-1.0, w_max=1.0)

# save SigmaContinuator again (now it contains S_w)
with HDFArchive('srvo3.h5', 'a') as ar:
    ar['isc'] = isc
# check linfit and plot S_w
fig1 = plt.figure()
plt.subplot(1, 2, 1)
for key in res:
    res[key].analyzer_results['LineFitAnalyzer'].plot_linefit()
plt.ylim(1e1, 1e4)
plt.subplot(1, 2, 2)
oplot(isc.S_w['up_0'], mode='I', label='maxent xy', lw=3)
oplot(isc.S_w['up_1'], mode='I', label='maxent xz', lw=3)
plt.ylabel(r'$\Sigma(\omega)$')
plt.xlim(-0.75, 0.75)
plt.ylim(-0.4, 0.0)
fig1.savefig('sigma_continuator_srvo3.png')
"
 But when I run these scripts for srvo3 compound instead of Sr2RuO4 compound, I have very bad results :(((

can you please help me to solving my problem?
thanks so much
Sincerely yours 
Reyhaneh

**Comment by mzingl** [comment]
Dear Reyaneh,

1.) Format your issues in way that they are easily readable to humans. Format code as code and text as text.

2.) Issue reports need to be prepared such that the error/problem can be easily reproduced. We neither know how your input looks like, nor how your output looks like. Describe what input data you use and where we can find it.

3.) It is impossible to provide any help if your issue is to get 'bad results'. 'It doesn't work' or 'I have very bad results' is not an issue report! Explain in detail what is happing and how the results look like.

If you are seeking help, than please make it as easy as possible for those who help.

Manuel

**Comment by Reyhanehe** [comment]
Dear Manuel
Thanks for your useful comment.
So I explain my problem more than before.
I used maxentropy method for conversion of S_iw to S_w. then I run the srvo3_transp.py  that is implemented in triqs code. But whwn I want run it I have the error that "dmft_transp_input" is not recognized. So for solving it I create a group with name "dmft_transp_input" and the rerun my calculation. in this step I have the error that in "Sigma = ar['dmft_transp_input']['Sigma_w']" Sigma_w is not found. for solving this I use "    isc = ar['isc']
Sigma = isc.S_w
" and then rerun my calculation.
after them I can run this script without any error but my result are not good.
for example I obtained -267.194965  x 10^(-6) V/K for seebeck in direction xx or 0.00000 x 10^4 Ohm^-1 cm^- for Conductivity in direction xx for Omega = 0.02 :( while I see in triqs code that these result should be "
Seebeck in direction      xx for Omega = 0.00      -717.194965  x 10^(-6) V/K
and 
Conductivity in direction xx for Omega = 0.02       0.012864  x 10^4 Ohm^-1 cm^-1"
Could you please help me to solve this issue?
notice that when I run this script in my "dmft_transp_input" the "dc_imp" is equal to zero matrix and also the "chemical_potential" is zero too, but I see in triqs code that these parameters are not zero. Is my bad result for this subject? 
I am so thanks full for you and anybody who can help me to solve this problem
thans a lot
Sincerely Yours
Reyhaneh

**Comment by mzingl** [comment]
1.) This is the maxent issue list, your problem is however connected to DFTTools. Next time make sure to post the issue on the correct list.
2.) maxent continues your Sigma(iw) to Sigma(w). 
3.) It seems that you are trying to use the 'srvo3_transp.py' test. Do not use this and the h5 files for your calculations!! This is only for the purpose of testing the code. For your transport calculations you will need your original h5 file from your DMFT calculation plus the self-energy from maxent, plus the chemical potential and dc_imp from your DMFT results.
4.) If you want to run transport calculation, please follow the steps outline in the documentation of the transport code: https://triqs.github.io/dft_tools/2.1.x/guide/transport.html
It is very well described there what you need to do.

Best, M

**Comment by Reyhanehe** [comment]
Dear Manuel
Thanks a lot for your very good answer to my issue.
I used case.h5 and other input files from my DMFT calculation but for knowing that is my calculation true or not I repeat my result with the result of transport calculation files in triqs code and see that my result is not agreement with the output of transport properties in test file of triqs code.
I thought that my calculation is wrong because the case_transp.py in triqs code is difference from the case_transp.py that is exist in: https://triqs.github.io/dft_tools/2.1.x/guide/transport.html
It is not important in these calculation?
thanks so much
Sicerely yours
Reyhaneh

**Comment by cmtcl18** [comment]
Dear Developers,
I want to convert Sigma_w from Sigma_iw using SigmaContinuator. For this purpose I used the above code that Reyhanehe has submitted here. I am getting  error.

The  relevant part of the code is
Aaux_w = {}
w = res['up_0'].omega
for key in res:
    Aaux_w[key] = res[key].analyzer_results['LineFitAnalyzer']['A_out']
isc.set_Gaux_w_from_Aaux_w(Aaux_w, w, np_interp_A=10000,
                           np_omega=4000, w_min=-1.0, w_max=1.0)


#### Save SigmaContinuator again (now it contains Sigma_w) ###
with HDFArchive('SrVO3_maxent.h5', 'a') as ar:
    ar['maxent_result_'] = res[key].data
    ar['isc'] = isc

The error is,
Traceback (most recent call last):
  File "maxent.py", line 52, in <module>
    w = res['up_0'].omega
AttributeError: 'Gf' object has no attribute 'omega'

I am gradually trying to investigate the physical interpretation of the code. Can anyone suggest,  what is the error here and how it can be sort-out?

Your suggestion will be helpful for me. 

Regards,
CMTCL
